//
//  InsightsView.swift
//  CalmSteps
//

import SwiftUI
import SwiftData

//tiny structt for the hardest steps list used to be a tuple but a named struct is easier to readdd
struct HardStep: Identifiable {
    let id = UUID()
    let title: String
    let count: Int
}

struct InsightsView: View {
    
    @ObservedObject var parentVM: ParentFlowViewModel
    
    @Query private var runs: [RoutineRun]
    @Query private var breaks: [BreakEvent]
    @Query private var moods: [MoodCheck]
    
    @StateObject private var insightEngine = InsightEngine()
    
    var body: some View {
        NavigationStack {
            ZStack {
                Color(.systemGroupedBackground)
                    .ignoresSafeArea()
                
                ScrollView(showsIndicators: false) {
                    VStack(spacing: 18) {
                        headerCard
                        aiCard
                        summaryCard
                        hardStepsCard
                        recentBreaksCard
                        recentMoodsCard
                    }
                    .padding()
                }
            }
            .navigationTitle("Insights")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    Button("Back") {
                        parentVM.goToDashboard()
                    }
                }
            }
            //.task runs once when the view appears kicks off the openai call (or offline
            .task {
                await insightEngine.generateSuggestion(from: breakEventsForAI)
            }
        }
    }
    
    private var headerCard: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text("Routine Insights")
                .font(.system(size: 18, weight: .bold))
            Text("See how routines are going and spot steps that need support")
                .font(.system(size: 14))
                .foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(16)
        .background(Color.blue.opacity(0.12))
        .clipShape(RoundedRectangle(cornerRadius: 18))
    }
    
    private var aiCard: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 8) {
                Image(systemName: "sparkles")
                    .foregroundStyle(.purple)
                Text("AI Suggestion")
                    .font(.headline)
            }
            
            if insightEngine.isLoading == true {
                HStack {
                    Spacer()
                    ProgressView()
                        .padding()
                    Spacer()
                }
            } else {
                Text(insightEngine.suggestion)
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
            
            Text("generated by ai based on your childs break history")
                .font(.caption2)
                .foregroundStyle(.tertiary)
        }
        .padding()
        .background(Color.purple.opacity(0.08))
        .clipShape(RoundedRectangle(cornerRadius: 20))
        .overlay {
            RoundedRectangle(cornerRadius: 20)
                .stroke(Color.purple.opacity(0.15), lineWidth: 1)
        }
    }
    
    private var summaryCard: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Summary").font(.headline)
            
            HStack(spacing: 12) {
                statBox(
                    value: "\(runs.count)",
                    label: "routines completed",
                    icon: "checkmark.circle.fill",
                    color: .blue
                )
                statBox(
                    value: "\(breaks.count)",
                    label: "breaks taken",
                    icon: "pause.circle.fill",
                    color: .orange
                )
            }
        }
        .padding()
        .background(Color(.secondarySystemGroupedBackground))
        .clipShape(RoundedRectangle(cornerRadius: 20))
    }
    
    private var hardStepsCard: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Steps Needing Support").font(.headline)
            
            if hardestSteps.isEmpty == true {
                Text("No repeated difficult steps yet.")
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            } else {
                ForEach(hardestSteps) { item in
                    hardStepRow(item: item)
                }
            }
        }
        .padding()
        .background(Color(.secondarySystemGroupedBackground))
        .clipShape(RoundedRectangle(cornerRadius: 20))
    }
    
    private func hardStepRow(item: HardStep) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack {
                Image(systemName: "exclamationmark.circle.fill")
                    .foregroundStyle(.orange)
                Text(item.title).fontWeight(.semibold)
                Spacer()
                Text("\(item.count) breaks")
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
            Text(supportMessage(count: item.count))
                .font(.footnote)
                .foregroundStyle(.secondary)
        }
        .padding()
        .background(Color(.systemBackground))
        .clipShape(RoundedRectangle(cornerRadius: 14))
    }
    
    private var recentBreaksCard: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Recent Breaks").font(.headline)
            
            if breaks.isEmpty == true {
                Text("No breaks recorded yet.")
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            } else {
                ForEach(recentBreaks, id: \.id) { event in
                    breakRow(event: event)
                }
            }
        }
        .padding()
        .background(Color(.secondarySystemGroupedBackground))
        .clipShape(RoundedRectangle(cornerRadius: 20))
    }
    
    private func breakRow(event: BreakEvent) -> some View {
        
        //yellow dot for morning, indigo for evening
        var dotColor = Color.indigo.opacity(0.6)
        if event.routineType == "morning" {
            dotColor = Color.yellow.opacity(0.6)
        }
        
        return HStack(spacing: 12) {
            Circle()
                .fill(dotColor)
                .frame(width: 10, height: 10)
            
            VStack(alignment: .leading, spacing: 4) {
                Text(event.stepTitle).fontWeight(.semibold)
                Text(event.routineType.capitalized + " routine")
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
            
            Spacer()
            
            Text(event.date.formatted(date: .abbreviated, time: .shortened))
                .font(.footnote)
                .foregroundStyle(.secondary)
        }
        .padding()
        .background(Color(.systemBackground))
        .clipShape(RoundedRectangle(cornerRadius: 14))
    }
    
    private var recentMoodsCard: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Recent Moods").font(.headline)
            
            if moods.isEmpty == true {
                Text("No mood checks recorded yet.")
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            } else {
                ForEach(recentMoods, id: \.id) { check in
                    moodRow(check: check)
                }
            }
        }
        .padding()
        .background(Color(.secondarySystemGroupedBackground))
        .clipShape(RoundedRectangle(cornerRadius: 20))
    }
    
    private func moodRow(check: MoodCheck) -> some View {
        HStack(spacing: 12) {
            Text(emoji(for: check.mood))
                .font(.system(size: 28))
            
            VStack(alignment: .leading, spacing: 4) {
                Text(check.mood.capitalized).fontWeight(.semibold)
                Text(check.routineType.capitalized + " routine")
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
            
            Spacer()
            
            Text(check.date.formatted(date: .abbreviated, time: .shortened))
                .font(.footnote)
                .foregroundStyle(.secondary)
        }
        .padding()
        .background(Color(.systemBackground))
        .clipShape(RoundedRectangle(cornerRadius: 14))
    }
    
    private func statBox(value: String, label: String, icon: String, color: Color) -> some View {
        VStack(spacing: 8) {
            Image(systemName: icon)
                .font(.system(size: 22))
                .foregroundStyle(color)
            Text(value)
                .font(.title2)
                .fontWeight(.bold)
            Text(label)
                .font(.footnote)
                .foregroundStyle(.secondary)
                .multilineTextAlignment(.center)
        }
        .frame(maxWidth: .infinity)
        .padding()
        .background(Color(.systemBackground))
        .clipShape(RoundedRectangle(cornerRadius: 16))
    }
    
    //just find 3 steps with most breaks simple lops and buble sort
    private var hardestSteps: [HardStep] {
        
        //collect every unique step title from the breaks list
        var uniqueTitles: [String] = []
        for event in breaks {
            var alreadySeen = false
            for existing in uniqueTitles {
                if existing == event.stepTitle {
                    alreadySeen = true
                }
            }
            if alreadySeen == false {
                uniqueTitles.append(event.stepTitle)
            }
        }
        
        
        var counted: [HardStep] = []
        for title in uniqueTitles {
            var count = 0
            for event in breaks {
                if event.stepTitle == title {
                    count = count + 1   //count how many breakes match each title
                }
            }
            let entry = HardStep(title: title, count: count)
            counted.append(entry)
        }
        
        //sort by count descendin
        var sorted = counted
        for i in 0..<sorted.count {
            for j in i+1..<sorted.count {
                if sorted[j].count > sorted[i].count {
                    let temp = sorted[i]
                    sorted[i] = sorted[j]
                    sorted[j] = temp
                }
            }
        }
        
        //keep only top 3
        var topThree: [HardStep] = []
        var picked = 0
        for item in sorted {
            if picked < 3 {
                topThree.append(item)
                picked = picked + 1
            }
        }
        
        return topThree
    }
    
    //most recent 10 breaks- bubble sort by date descending then take 10
    private var recentBreaks: [BreakEvent] {
        
        var sorted = breaks
        for i in 0..<sorted.count {
            for j in i+1..<sorted.count {
                if sorted[j].date > sorted[i].date {
                    let temp = sorted[i]
                    sorted[i] = sorted[j]
                    sorted[j] = temp
                }
            }
        }
        
        var topTen: [BreakEvent] = []
        var picked = 0
        for item in sorted {
            if picked < 10 {
                topTen.append(item)
                picked = picked + 1
            }
        }
        
        return topTen
    }
    
    //most recent 5 moods- same pattern as recentBreaks
    private var recentMoods: [MoodCheck] {
        
        var sorted = moods
        for i in 0..<sorted.count {
            for j in i+1..<sorted.count {
                if sorted[j].date > sorted[i].date {
                    let temp = sorted[i]
                    sorted[i] = sorted[j]
                    sorted[j] = temp
                }
            }
        }
        
        var topFive: [MoodCheck] = []
        var picked = 0
        for item in sorted {
            if picked < 5 {
                topFive.append(item)
                picked = picked + 1
            }
        }
        
        return topFive
    }
    
    //hardestSteps but as tuples for the InsightEngine signature
    private var breakEventsForAI: [(title: String, count: Int)] {
        var result: [(title: String, count: Int)] = []
        for item in hardestSteps {
            result.append((title: item.title, count: item.count))
        }
        return result
    }
    
    private func supportMessage(count: Int) -> String {
        if count >= 5 {
            return "This step seems really tricky — maybe try splitting it into smaller parts."
        } else if count >= 3 {
            return "A few breaks here — consider adding a photo or voice guidance."
        } else {
            return "Keep an eye on this step."
        }
    }
    
    private func emoji(for mood: String) -> String {
        if mood == "happy" {
            return "😊"
        } else if mood == "okay" {
            return "😐"
        } else if mood == "sad" {
            return "😢"
        } else {
            return "❓"
        }
    }
}

#Preview {
    InsightsView(parentVM: ParentFlowViewModel())
}
